name: 'Setup Project'
description: 'Checkout, set up Java and prepare Gradle'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash # Composite actions require specifying the shell
      run: chmod +x gradlew